# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/dashboard
---
version: 2.1
jobs:
  build:
    parameters:
      publish:
        type: boolean
    # https://circleci.com/docs/2.0/circleci-images/
    docker: [ image: circleci/buildpack-deps:unstable-scm ]
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          sudo curl -L -o /usr/local/bin/dobi \
            "https://github.com/dnephin/dobi/releases/download/v0.12.0/dobi-$(uname -s)"
          sudo chmod +x /usr/local/bin/dobi
      - run: |
          cd ~/project
          dobi
      - when:
          condition: << parameters.publish >>
          steps:
            - run: docker push eerorika/build-cpp:runtime
workflows:
  build:
    jobs:
      - build:
          publish: true
          filters:
            branches: { only: master }
      - build:
          publish: false
          filters:
            branches: { ignore: master }
